# Cockburn Environmental Data

## Cockburn Sound data collation {-}

As an ongoing process throughout the project, data from WAMSI research, as well as third party data providers is being collated, catalogued and standardised for a wide range of use-cases, users and platforms.  In order to accomodate these demands, data is rigoriously catalogued and processed into a common format. Raw data is stored in a data lake found on the csiem-data github repository, in the ```incoming``` directory. The data lake is organised via data provider (Agency ID), and the via a specific specific project identifier. 







## Cockburn Sound environmental data categories {-}

All data available for model setup and validation has been compiled, from WAMSI research, prior research and routine monitoring (see [Chapter 3](Model-Data Ecosystem)). Data is categorised in the general areas of :

+ *Bathymetry*
+ *Meteorology*
+ *Hydrology*
+ *Water Quality*
+ *Sediment*
+ *Biota*


These are defined into sub-categories, as outlined in Table \@ref(tab:data-classes).

<br>

```{r data-classes, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(readxl)
library(rmarkdown)
theSheet <- read_excel('tables/CDM_Classes.xlsx', sheet = 2)
theSheet <- theSheet[theSheet$Table == "Data",]
theSheetGroups <- unique(theSheet$Group)

kbl(theSheet[,3:4], caption = "CSIEM Data Classification", align = "l",) %>%

row_spec(0, background = "#002B4D", bold = TRUE, color = "white") %>%
  kable_styling(full_width = T,font_size = 10) %>%
    scroll_box(fixed_thead = FALSE)
```

<br>
